updated

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -93,38 +93,38 @@ runs:
           fi
         fi
 
-        echo docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:3.88.1 git file:///pwd --json --no-update $BRANCH_FLAG $RESULTS_FLAG $EXTENDED_RULESET $FAIL_FLAG $EXCLUDE_FLAG $EXTRA_ARGS > trufflehog-results.json || exit_code=$?
+        echo docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:3.88.1 git file:///pwd --json --no-update $BRANCH_FLAG $RESULTS_FLAG $EXTENDED_RULESET $FAIL_FLAG $EXCLUDE_FLAG $EXTRA_ARGS
         
-        docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:3.88.1 git file:///pwd --json --no-update $BRANCH_FLAG $RESULTS_FLAG $EXTENDED_RULESET $FAIL_FLAG $EXCLUDE_FLAG $EXTRA_ARGS > trufflehog-results.json || exit_code=$?
+        # docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:3.88.1 git file:///pwd --json --no-update $BRANCH_FLAG $RESULTS_FLAG $EXTENDED_RULESET $FAIL_FLAG $EXCLUDE_FLAG $EXTRA_ARGS > trufflehog-results.json || exit_code=$?
         
-        echo "TRUFFLEHOG_EXIT_CODE=${exit_code:-0}" >> $GITHUB_ENV
+        # echo "TRUFFLEHOG_EXIT_CODE=${exit_code:-0}" >> $GITHUB_ENV
       shell: bash
 
-    - name: Push report to Control Plane
-      run: |
-        if [[ ! -s trufflehog-results.json ]]; then
-          echo "No secrets found. Skipping API upload."
-          exit 0
-        fi
+    # - name: Push report to Control Plane
+    #   run: |
+    #     if [[ ! -s trufflehog-results.json ]]; then
+    #       echo "No secrets found. Skipping API upload."
+    #       exit 0
+    #     fi
         
-        RESPONSE=$(curl --location 'https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=TruffleHog&save_to_s3=true&label_id=${{ inputs.label }}' \
-            --header 'Tenant-Id: ${{ inputs.tenant_id }}' \
-            --header 'Authorization: Bearer ${{ inputs.token }}' \
-            --form 'file=@./trufflehog-results.json')
+    #     RESPONSE=$(curl --location 'https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=TruffleHog&save_to_s3=true&label_id=${{ inputs.label }}' \
+    #         --header 'Tenant-Id: ${{ inputs.tenant_id }}' \
+    #         --header 'Authorization: Bearer ${{ inputs.token }}' \
+    #         --form 'file=@./trufflehog-results.json')
 
-            echo "Response: $RESPONSE"
-            if [[ "$RESPONSE" != *"File received successfully"* ]]; then
-              echo "Error: Failed to push report to control plane"
-              exit 1
-            fi
-      shell: bash
+    #         echo "Response: $RESPONSE"
+    #         if [[ "$RESPONSE" != *"File received successfully"* ]]; then
+    #           echo "Error: Failed to push report to control plane"
+    #           exit 1
+    #         fi
+    #   shell: bash
 
-    - name: Quality Check with exit_code
-      if: env.TRUFFLEHOG_EXIT_CODE == '183'
-      run: |
-        echo "Scan Engine found credentials. Failing the job."
-        exit 1
-      shell: bash
+    # - name: Quality Check with exit_code
+    #   if: env.TRUFFLEHOG_EXIT_CODE == '183'
+    #   run: |
+    #     echo "Scan Engine found credentials. Failing the job."
+    #     exit 1
+    #   shell: bash
 
 branding:
   icon: "lock"
