updated

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,6 +10,15 @@ inputs:
     description: "The ID of the tenant associated with the control plane."
     required: true
 
+  secret_scan_type:
+    description: "Source type for scanning (git, huggingface, s3)"
+    required: true
+    default: "git"
+    options: 
+      - git
+      - huggingface
+      - s3
+
   label:
     description: "The label created in AccuKnox SaaS for associating scan results."
     required: true
@@ -36,6 +45,14 @@ inputs:
     description: "Paths to exclude from the scan."
     required: false
 
+  dataset:
+    description: "Dataset name (required if secret_scan_type is 'huggingface')"
+    required: false
+
+  huggingface_token:
+    description: "Huggingface Token (required if secret_scan_type is 'huggingface')"
+    required: false
+
   use_extended_ruleset:
     description: "Enable extended regex rules for detecting sensitive data"
     required: false
@@ -55,6 +72,8 @@ runs:
   steps:
     - name: Run Secrets Scan engine
       run: |
+        SECRET_SCAN_TYPE=""
+
         RESULTS_FLAG=""
         if [[ -n "${{ inputs.results }}" ]]; then
           RESULTS_FLAG="--results ${{ inputs.results }}"
@@ -63,11 +82,6 @@ runs:
         FAIL_FLAG=""
         if [[ "${{ inputs.fail }}" == "true" ]]; then
           FAIL_FLAG="--fail"
-        fi
-
-        EXCLUDE_FLAG=""
-        if [[ -n "${{ inputs.exclude-paths }}" ]]; then
-          EXCLUDE_FLAG="-x /pwd/${{ inputs.exclude-paths }}"
         fi
 
         EXTRA_ARGS=""
@@ -88,20 +102,44 @@ runs:
             CONFIG_OPTION=""
         fi
 
+        EXCLUDE_FLAG=""
         BRANCH_FLAG=""
-        if [[ "${{ inputs.branch }}" == "all-branches" ]]; then
-          BRANCH_FLAG=""
-        elif [[ -n "${{ inputs.branch }}" ]]; then
-          BRANCH_FLAG="--branch=${{ inputs.branch }}"
-        else
-          if [[ -n "${{ github.event.pull_request.head.ref }}" ]]; then
-            BRANCH_FLAG="--branch=${{ github.event.pull_request.head.ref }}"
+        if [[ "${{ inputs.secret_scan_type }}" == "git" ]]; then
+          SECRET_SCAN_TYPE="git file:///pwd"
+
+          if [[ -n "${{ inputs.exclude-paths }}" ]]; then
+            EXCLUDE_FLAG="-x /pwd/${{ inputs.exclude-paths }}"
+          fi
+
+          if [[ "${{ inputs.branch }}" == "all-branches" ]]; then
+            BRANCH_FLAG=""
+          elif [[ -n "${{ inputs.branch }}" ]]; then
+            BRANCH_FLAG="--branch=${{ inputs.branch }}"
           else
-            BRANCH_FLAG="--branch=${{ github.ref_name }}"
+            if [[ -n "${{ github.event.pull_request.head.ref }}" ]]; then
+              BRANCH_FLAG="--branch=${{ github.event.pull_request.head.ref }}"
+            else
+              BRANCH_FLAG="--branch=${{ github.ref_name }}"
+            fi
           fi
         fi
+        DATASET_FLAG=""
+        if [[ "${{ inputs.secret_scan_type }}" == "huggingface" ]]; then
+          SECRET_SCAN_TYPE="huggingface"
+          if [[ -z "${{ inputs.dataset }}" ]]; then
+            echo "Error: 'dataset' input is required when secret_scan_type is 'huggingface'."
+            exit 1
+          fi
+          if [[ -z "${{ inputs.huggingface_token }}" ]]; then
+            echo "Error: 'huggingface_token' input is required when secret_scan_type is 'huggingface'."
+            exit 1
+          fi
+          DATASET_FLAG="--dataset=${{ inputs.dataset }}"
+        fi
 
-        docker run --rm -v $PWD/extended_ruleset_path.yml:/extended_ruleset_path.yml -v "$PWD:/pwd" trufflesecurity/trufflehog:3.88.1 git file:///pwd --json --no-update $BRANCH_FLAG $RESULTS_FLAG $CONFIG_OPTION $FAIL_FLAG $EXCLUDE_FLAG $EXTRA_ARGS > trufflehog-results.json || exit_code=$?
+        echo docker run --rm -e HUGGINGFACE_TOKEN="${{ inputs.huggingface_token }}" -v $PWD/extended_ruleset_path.yml:/extended_ruleset_path.yml -v "$PWD:/pwd" trufflesecurity/trufflehog:3.88.1 $SECRET_SCAN_TYPE --json --no-update $BRANCH_FLAG $RESULTS_FLAG $CONFIG_OPTION $FAIL_FLAG $EXCLUDE_FLAG $EXTRA_ARGS 
+        
+        docker run --rm -e HUGGINGFACE_TOKEN="${{ inputs.huggingface_token }}" -v $PWD/extended_ruleset_path.yml:/extended_ruleset_path.yml -v "$PWD:/pwd" trufflesecurity/trufflehog:3.88.1 $SECRET_SCAN_TYPE --json --no-update $BRANCH_FLAG $RESULTS_FLAG $CONFIG_OPTION $FAIL_FLAG $EXCLUDE_FLAG $EXTRA_ARGS > trufflehog-results.json || exit_code=$?
         
         echo "TRUFFLEHOG_EXIT_CODE=${exit_code:-0}" >> $GITHUB_ENV
       shell: bash
